### ISSUE TITLE
Release 0.3.0

### ISSUE THREAD

**Issue by dlorenc** [sigstore/cosign#183]
Tracking bug for info related to the next release, 0.3.0. This will follow #130.

Things we need to get in:

- [x] #88 (rollover from last time)
- [ ] #117 and #131 (better KMS ux in general)
- [x] #115 Publish a release container for other integrations (right now it's just CI I believe)
- [x] #127 Improve code quality/refactoring
- [ ] #87 Don't need this in place yet, but a plan would be good

Add any other ideas below!
