### ISSUE TITLE
Release 0.4.0

### ISSUE THREAD

**Issue by dlorenc** [sigstore/cosign#269]
Stuff to get in!

- [ ] #254 (spec stability in general)
- [x] #250 (pending testing against registries)
- [ ] #195 (this would be fun)
- [x] #249 (dual-tag for a release)
- [x] #273 (e2e tests)

What else?

**Comment by dekkagaijin** [comment]
v0.4.0 released: https://github.com/sigstore/cosign/releases/tag/v0.4.0
